#!/bin/bash
# ==========================================
# Generate Embedded SDK Header for macOS
# Converts anywp_sdk.js to Objective-C string constant
# ==========================================

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

SDK_SOURCE="$PROJECT_ROOT/macos/Resources/anywp_sdk.js"
OUTPUT_HEADER="$PROJECT_ROOT/macos/Classes/Utils/EmbeddedSDK.h"
OUTPUT_IMPL="$PROJECT_ROOT/macos/Classes/Utils/EmbeddedSDK.m"

echo "========================================="
echo " Generating Embedded SDK for macOS"
echo "========================================="
echo ""
echo "Source: $SDK_SOURCE"
echo "Output: $OUTPUT_HEADER / $OUTPUT_IMPL"
echo ""

# Check if SDK file exists
if [ ! -f "$SDK_SOURCE" ]; then
    echo "ERROR: SDK file not found: $SDK_SOURCE"
    exit 1
fi

# Get SDK file size
SDK_SIZE=$(wc -c < "$SDK_SOURCE" | tr -d ' ')
echo "SDK Size: $SDK_SIZE bytes"
echo ""

# Generate Header File
cat > "$OUTPUT_HEADER" << 'EOF'
//
// EmbeddedSDK.h
// AnyWP Engine - Embedded JavaScript SDK
//
// This file is AUTO-GENERATED by scripts/generate_embedded_sdk_macos.sh
// DO NOT EDIT MANUALLY!
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/// Provides access to the embedded AnyWP JavaScript SDK
@interface EmbeddedSDK : NSObject

/// Returns the embedded SDK script as an NSString
+ (NSString *)getSDKScript;

/// Returns the SDK version
+ (NSString *)getSDKVersion;

@end

NS_ASSUME_NONNULL_END
EOF

echo "[1/2] Generated header file"

# Generate Implementation File
cat > "$OUTPUT_IMPL" << 'EOF_HEADER'
//
// EmbeddedSDK.m
// AnyWP Engine - Embedded JavaScript SDK
//
// This file is AUTO-GENERATED by scripts/generate_embedded_sdk_macos.sh
// DO NOT EDIT MANUALLY!
//

#import "EmbeddedSDK.h"

@implementation EmbeddedSDK

+ (NSString *)getSDKVersion {
    return @"2.5.0";
}

+ (NSString *)getSDKScript {
    // Embedded SDK script (compressed into single string literal)
    // Source: macos/Resources/anywp_sdk.js
    static NSString *sdkScript = nil;
    static dispatch_once_t onceToken;
    
    dispatch_once(&onceToken, ^{
        sdkScript = @
EOF_HEADER

# Convert JS file to Objective-C string literal
# Each line needs to be escaped and quoted
echo "Converting SDK to Objective-C string..."

# Use sed and awk to process the file
# 1. Escape backslashes: \ -> \\
# 2. Escape double quotes: " -> \"
# 3. Add quotes and line continuation: "line\n"
sed 's/\\/\\\\/g' "$SDK_SOURCE" | \
sed 's/"/\\"/g' | \
awk '{print "\"" $0 "\\n\""}' >> "$OUTPUT_IMPL"

# Close the string literal and function
cat >> "$OUTPUT_IMPL" << 'EOF_FOOTER'
        ;
    });
    
    return sdkScript;
}

@end
EOF_FOOTER

echo "[2/2] Generated implementation file"
echo ""
echo "========================================="
echo " Embedded SDK Generation Complete!"
echo "========================================="
echo ""
echo "Generated files:"
echo "  - $OUTPUT_HEADER"
echo "  - $OUTPUT_IMPL"
echo ""
echo "Next steps:"
echo "  1. Add these files to Xcode project (if not already)"
echo "  2. Update MessageBridge.m to use EmbeddedSDK"
echo "  3. Rebuild the plugin"
echo ""

exit 0

