//
// EmbeddedSDK.h
// AnyWP Engine - Embedded JavaScript SDK
//
// This file is AUTO-GENERATED by scripts/generate_embedded_sdk_macos.sh
// DO NOT EDIT MANUALLY!
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/// Provides access to the embedded AnyWP JavaScript SDK
@interface EmbeddedSDK : NSObject

/// Returns the embedded SDK script as an NSString
+ (NSString *)getSDKScript;

/// Returns the SDK version
+ (NSString *)getSDKVersion;

@end

NS_ASSUME_NONNULL_END
